/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Controlador.controlador;

/**
 *
 * @author Carla
 */
public class vista extends javax.swing.JFrame {
    
    int indice=0;
    String[] dni = new String[10];
    String[] nombre = new String[10];
    String[] apellido = new String[10];
    String[] direccion = new String[10];
    String[] telefono= new String[10];
    String[] fecha = new String[10];
       
    
    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        t_indice.setText(""+indice);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        j_panel2 = new javax.swing.JPanel();
        t_dni = new javax.swing.JTextField();
        t_apellido = new javax.swing.JTextField();
        t_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_direccion = new javax.swing.JTextField();
        t_telefono = new javax.swing.JTextField();
        t_fecha = new javax.swing.JTextField();
        j_panel3 = new javax.swing.JPanel();
        b_guardar = new javax.swing.JButton();
        b_anterior = new javax.swing.JButton();
        b_siguiente = new javax.swing.JButton();
        j_panel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        t_indice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenidos");

        j_panel1.setBackground(new java.awt.Color(153, 153, 255));
        j_panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AGENDA ELECTRONICA");

        javax.swing.GroupLayout j_panel1Layout = new javax.swing.GroupLayout(j_panel1);
        j_panel1.setLayout(j_panel1Layout);
        j_panel1Layout.setHorizontalGroup(
            j_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        j_panel1Layout.setVerticalGroup(
            j_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        j_panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        j_panel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel2.setText("DNI");

        jLabel3.setText("APELLIDO");

        jLabel4.setText("NOMBRE");

        jLabel5.setText("DIRECCION");

        jLabel6.setText("TELEFONO");

        jLabel7.setText("FECHA NACIMIENTO");

        javax.swing.GroupLayout j_panel2Layout = new javax.swing.GroupLayout(j_panel2);
        j_panel2.setLayout(j_panel2Layout);
        j_panel2Layout.setHorizontalGroup(
            j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_panel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_fecha))
                    .addGroup(j_panel2Layout.createSequentialGroup()
                        .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(61, 61, 61)
                        .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(t_telefono))))
                .addContainerGap())
        );
        j_panel2Layout.setVerticalGroup(
            j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(t_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(t_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(j_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        j_panel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        b_guardar.setText("GUARDAR");
        b_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_guardarMouseClicked(evt);
            }
        });
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        b_anterior.setText("ANTERIOR");
        b_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anteriorActionPerformed(evt);
            }
        });

        b_siguiente.setText("SIGUIENTE");
        b_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j_panel3Layout = new javax.swing.GroupLayout(j_panel3);
        j_panel3.setLayout(j_panel3Layout);
        j_panel3Layout.setHorizontalGroup(
            j_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_anterior)
                .addGap(44, 44, 44)
                .addComponent(b_guardar)
                .addGap(43, 43, 43)
                .addComponent(b_siguiente)
                .addGap(106, 106, 106))
        );
        j_panel3Layout.setVerticalGroup(
            j_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_guardar)
                    .addComponent(b_anterior)
                    .addComponent(b_siguiente))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        j_panel4.setBackground(new java.awt.Color(153, 153, 255));
        j_panel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("INDICE");

        t_indice.setEditable(false);

        javax.swing.GroupLayout j_panel4Layout = new javax.swing.GroupLayout(j_panel4);
        j_panel4.setLayout(j_panel4Layout);
        j_panel4Layout.setHorizontalGroup(
            j_panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel4Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_indice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j_panel4Layout.setVerticalGroup(
            j_panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_panel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(j_panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(j_panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(j_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(j_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(j_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j_panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b_guardarMouseClicked

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // Se obtienen los datos ingresados utilizando el comando "getText" y se los almacena en los vectores.
        dni[indice]=t_dni.getText();
        apellido[indice]=t_apellido.getText();
        nombre[indice]=t_nombre.getText();
        direccion[indice]=t_direccion.getText();
        telefono[indice]=t_telefono.getText();
        fecha[indice]=t_fecha.getText();
       
    }//GEN-LAST:event_b_guardarActionPerformed

    private void b_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_siguienteActionPerformed
        // En el boton "siguiente", se llama a un procedimiento llamado "siguiente" que se encuentra en el package "Controlador"
               indice=controlador.siguiente(indice);
               t_indice.setText(String.valueOf(indice));
               t_dni.setText(dni[indice]);
               t_apellido.setText(apellido[indice]);
               t_nombre.setText(nombre[indice]);
               t_direccion.setText(direccion[indice]);
               t_telefono.setText(telefono[indice]);
               t_fecha.setText(fecha[indice]);
            
          
       
    }//GEN-LAST:event_b_siguienteActionPerformed

    private void b_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anteriorActionPerformed
        //En el boton "anterior", se llama a un procedimiento llamado "anterior" que se encuentra en el package "Controlador"
               indice=controlador.anterior(indice);
               t_indice.setText(String.valueOf(indice));
               t_dni.setText(dni[indice]);
               t_apellido.setText(apellido[indice]);
               t_nombre.setText(nombre[indice]);
               t_direccion.setText(direccion[indice]);
               t_telefono.setText(telefono[indice]);
               t_fecha.setText(fecha[indice]);
            
        
    }//GEN-LAST:event_b_anteriorActionPerformed
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_anterior;
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton b_siguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel j_panel1;
    private javax.swing.JPanel j_panel2;
    private javax.swing.JPanel j_panel3;
    private javax.swing.JPanel j_panel4;
    private javax.swing.JTextField t_apellido;
    private javax.swing.JTextField t_direccion;
    private javax.swing.JTextField t_dni;
    private javax.swing.JTextField t_fecha;
    private javax.swing.JTextField t_indice;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_telefono;
    // End of variables declaration//GEN-END:variables
}
